require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InvoiceheadsController do

  # This should return the minimal set of attributes required to create a valid
  # Invoicehead. As you add validations to Invoicehead, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all invoiceheads as @invoiceheads" do
      invoicehead = Invoicehead.create! valid_attributes
      get :index
      assigns(:invoiceheads).should eq([invoicehead])
    end
  end

  describe "GET show" do
    it "assigns the requested invoicehead as @invoicehead" do
      invoicehead = Invoicehead.create! valid_attributes
      get :show, :id => invoicehead.id.to_s
      assigns(:invoicehead).should eq(invoicehead)
    end
  end

  describe "GET new" do
    it "assigns a new invoicehead as @invoicehead" do
      get :new
      assigns(:invoicehead).should be_a_new(Invoicehead)
    end
  end

  describe "GET edit" do
    it "assigns the requested invoicehead as @invoicehead" do
      invoicehead = Invoicehead.create! valid_attributes
      get :edit, :id => invoicehead.id.to_s
      assigns(:invoicehead).should eq(invoicehead)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Invoicehead" do
        expect {
          post :create, :invoicehead => valid_attributes
        }.to change(Invoicehead, :count).by(1)
      end

      it "assigns a newly created invoicehead as @invoicehead" do
        post :create, :invoicehead => valid_attributes
        assigns(:invoicehead).should be_a(Invoicehead)
        assigns(:invoicehead).should be_persisted
      end

      it "redirects to the created invoicehead" do
        post :create, :invoicehead => valid_attributes
        response.should redirect_to(Invoicehead.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved invoicehead as @invoicehead" do
        # Trigger the behavior that occurs when invalid params are submitted
        Invoicehead.any_instance.stub(:save).and_return(false)
        post :create, :invoicehead => {}
        assigns(:invoicehead).should be_a_new(Invoicehead)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Invoicehead.any_instance.stub(:save).and_return(false)
        post :create, :invoicehead => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested invoicehead" do
        invoicehead = Invoicehead.create! valid_attributes
        # Assuming there are no other invoiceheads in the database, this
        # specifies that the Invoicehead created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Invoicehead.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => invoicehead.id, :invoicehead => {'these' => 'params'}
      end

      it "assigns the requested invoicehead as @invoicehead" do
        invoicehead = Invoicehead.create! valid_attributes
        put :update, :id => invoicehead.id, :invoicehead => valid_attributes
        assigns(:invoicehead).should eq(invoicehead)
      end

      it "redirects to the invoicehead" do
        invoicehead = Invoicehead.create! valid_attributes
        put :update, :id => invoicehead.id, :invoicehead => valid_attributes
        response.should redirect_to(invoicehead)
      end
    end

    describe "with invalid params" do
      it "assigns the invoicehead as @invoicehead" do
        invoicehead = Invoicehead.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Invoicehead.any_instance.stub(:save).and_return(false)
        put :update, :id => invoicehead.id.to_s, :invoicehead => {}
        assigns(:invoicehead).should eq(invoicehead)
      end

      it "re-renders the 'edit' template" do
        invoicehead = Invoicehead.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Invoicehead.any_instance.stub(:save).and_return(false)
        put :update, :id => invoicehead.id.to_s, :invoicehead => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested invoicehead" do
      invoicehead = Invoicehead.create! valid_attributes
      expect {
        delete :destroy, :id => invoicehead.id.to_s
      }.to change(Invoicehead, :count).by(-1)
    end

    it "redirects to the invoiceheads list" do
      invoicehead = Invoicehead.create! valid_attributes
      delete :destroy, :id => invoicehead.id.to_s
      response.should redirect_to(invoiceheads_url)
    end
  end

end
