require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InvoicelinesController do

  # This should return the minimal set of attributes required to create a valid
  # Invoiceline. As you add validations to Invoiceline, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all invoicelines as @invoicelines" do
      invoiceline = Invoiceline.create! valid_attributes
      get :index
      assigns(:invoicelines).should eq([invoiceline])
    end
  end

  describe "GET show" do
    it "assigns the requested invoiceline as @invoiceline" do
      invoiceline = Invoiceline.create! valid_attributes
      get :show, :id => invoiceline.id.to_s
      assigns(:invoiceline).should eq(invoiceline)
    end
  end

  describe "GET new" do
    it "assigns a new invoiceline as @invoiceline" do
      get :new
      assigns(:invoiceline).should be_a_new(Invoiceline)
    end
  end

  describe "GET edit" do
    it "assigns the requested invoiceline as @invoiceline" do
      invoiceline = Invoiceline.create! valid_attributes
      get :edit, :id => invoiceline.id.to_s
      assigns(:invoiceline).should eq(invoiceline)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Invoiceline" do
        expect {
          post :create, :invoiceline => valid_attributes
        }.to change(Invoiceline, :count).by(1)
      end

      it "assigns a newly created invoiceline as @invoiceline" do
        post :create, :invoiceline => valid_attributes
        assigns(:invoiceline).should be_a(Invoiceline)
        assigns(:invoiceline).should be_persisted
      end

      it "redirects to the created invoiceline" do
        post :create, :invoiceline => valid_attributes
        response.should redirect_to(Invoiceline.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved invoiceline as @invoiceline" do
        # Trigger the behavior that occurs when invalid params are submitted
        Invoiceline.any_instance.stub(:save).and_return(false)
        post :create, :invoiceline => {}
        assigns(:invoiceline).should be_a_new(Invoiceline)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Invoiceline.any_instance.stub(:save).and_return(false)
        post :create, :invoiceline => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested invoiceline" do
        invoiceline = Invoiceline.create! valid_attributes
        # Assuming there are no other invoicelines in the database, this
        # specifies that the Invoiceline created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Invoiceline.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => invoiceline.id, :invoiceline => {'these' => 'params'}
      end

      it "assigns the requested invoiceline as @invoiceline" do
        invoiceline = Invoiceline.create! valid_attributes
        put :update, :id => invoiceline.id, :invoiceline => valid_attributes
        assigns(:invoiceline).should eq(invoiceline)
      end

      it "redirects to the invoiceline" do
        invoiceline = Invoiceline.create! valid_attributes
        put :update, :id => invoiceline.id, :invoiceline => valid_attributes
        response.should redirect_to(invoiceline)
      end
    end

    describe "with invalid params" do
      it "assigns the invoiceline as @invoiceline" do
        invoiceline = Invoiceline.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Invoiceline.any_instance.stub(:save).and_return(false)
        put :update, :id => invoiceline.id.to_s, :invoiceline => {}
        assigns(:invoiceline).should eq(invoiceline)
      end

      it "re-renders the 'edit' template" do
        invoiceline = Invoiceline.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Invoiceline.any_instance.stub(:save).and_return(false)
        put :update, :id => invoiceline.id.to_s, :invoiceline => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested invoiceline" do
      invoiceline = Invoiceline.create! valid_attributes
      expect {
        delete :destroy, :id => invoiceline.id.to_s
      }.to change(Invoiceline, :count).by(-1)
    end

    it "redirects to the invoicelines list" do
      invoiceline = Invoiceline.create! valid_attributes
      delete :destroy, :id => invoiceline.id.to_s
      response.should redirect_to(invoicelines_url)
    end
  end

end
