require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProvenancesController do

  # This should return the minimal set of attributes required to create a valid
  # Provenance. As you add validations to Provenance, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all provenances as @provenances" do
      provenance = Provenance.create! valid_attributes
      get :index
      assigns(:provenances).should eq([provenance])
    end
  end

  describe "GET show" do
    it "assigns the requested provenance as @provenance" do
      provenance = Provenance.create! valid_attributes
      get :show, :id => provenance.id.to_s
      assigns(:provenance).should eq(provenance)
    end
  end

  describe "GET new" do
    it "assigns a new provenance as @provenance" do
      get :new
      assigns(:provenance).should be_a_new(Provenance)
    end
  end

  describe "GET edit" do
    it "assigns the requested provenance as @provenance" do
      provenance = Provenance.create! valid_attributes
      get :edit, :id => provenance.id.to_s
      assigns(:provenance).should eq(provenance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Provenance" do
        expect {
          post :create, :provenance => valid_attributes
        }.to change(Provenance, :count).by(1)
      end

      it "assigns a newly created provenance as @provenance" do
        post :create, :provenance => valid_attributes
        assigns(:provenance).should be_a(Provenance)
        assigns(:provenance).should be_persisted
      end

      it "redirects to the created provenance" do
        post :create, :provenance => valid_attributes
        response.should redirect_to(Provenance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved provenance as @provenance" do
        # Trigger the behavior that occurs when invalid params are submitted
        Provenance.any_instance.stub(:save).and_return(false)
        post :create, :provenance => {}
        assigns(:provenance).should be_a_new(Provenance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Provenance.any_instance.stub(:save).and_return(false)
        post :create, :provenance => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested provenance" do
        provenance = Provenance.create! valid_attributes
        # Assuming there are no other provenances in the database, this
        # specifies that the Provenance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Provenance.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => provenance.id, :provenance => {'these' => 'params'}
      end

      it "assigns the requested provenance as @provenance" do
        provenance = Provenance.create! valid_attributes
        put :update, :id => provenance.id, :provenance => valid_attributes
        assigns(:provenance).should eq(provenance)
      end

      it "redirects to the provenance" do
        provenance = Provenance.create! valid_attributes
        put :update, :id => provenance.id, :provenance => valid_attributes
        response.should redirect_to(provenance)
      end
    end

    describe "with invalid params" do
      it "assigns the provenance as @provenance" do
        provenance = Provenance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Provenance.any_instance.stub(:save).and_return(false)
        put :update, :id => provenance.id.to_s, :provenance => {}
        assigns(:provenance).should eq(provenance)
      end

      it "re-renders the 'edit' template" do
        provenance = Provenance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Provenance.any_instance.stub(:save).and_return(false)
        put :update, :id => provenance.id.to_s, :provenance => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested provenance" do
      provenance = Provenance.create! valid_attributes
      expect {
        delete :destroy, :id => provenance.id.to_s
      }.to change(Provenance, :count).by(-1)
    end

    it "redirects to the provenances list" do
      provenance = Provenance.create! valid_attributes
      delete :destroy, :id => provenance.id.to_s
      response.should redirect_to(provenances_url)
    end
  end

end
