require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RatesController do

  # This should return the minimal set of attributes required to create a valid
  # Rate. As you add validations to Rate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all rates as @rates" do
      rate = Rate.create! valid_attributes
      get :index
      assigns(:rates).should eq([rate])
    end
  end

  describe "GET show" do
    it "assigns the requested rate as @rate" do
      rate = Rate.create! valid_attributes
      get :show, :id => rate.id.to_s
      assigns(:rate).should eq(rate)
    end
  end

  describe "GET new" do
    it "assigns a new rate as @rate" do
      get :new
      assigns(:rate).should be_a_new(Rate)
    end
  end

  describe "GET edit" do
    it "assigns the requested rate as @rate" do
      rate = Rate.create! valid_attributes
      get :edit, :id => rate.id.to_s
      assigns(:rate).should eq(rate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rate" do
        expect {
          post :create, :rate => valid_attributes
        }.to change(Rate, :count).by(1)
      end

      it "assigns a newly created rate as @rate" do
        post :create, :rate => valid_attributes
        assigns(:rate).should be_a(Rate)
        assigns(:rate).should be_persisted
      end

      it "redirects to the created rate" do
        post :create, :rate => valid_attributes
        response.should redirect_to(Rate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rate as @rate" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rate.any_instance.stub(:save).and_return(false)
        post :create, :rate => {}
        assigns(:rate).should be_a_new(Rate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rate.any_instance.stub(:save).and_return(false)
        post :create, :rate => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rate" do
        rate = Rate.create! valid_attributes
        # Assuming there are no other rates in the database, this
        # specifies that the Rate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Rate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => rate.id, :rate => {'these' => 'params'}
      end

      it "assigns the requested rate as @rate" do
        rate = Rate.create! valid_attributes
        put :update, :id => rate.id, :rate => valid_attributes
        assigns(:rate).should eq(rate)
      end

      it "redirects to the rate" do
        rate = Rate.create! valid_attributes
        put :update, :id => rate.id, :rate => valid_attributes
        response.should redirect_to(rate)
      end
    end

    describe "with invalid params" do
      it "assigns the rate as @rate" do
        rate = Rate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rate.any_instance.stub(:save).and_return(false)
        put :update, :id => rate.id.to_s, :rate => {}
        assigns(:rate).should eq(rate)
      end

      it "re-renders the 'edit' template" do
        rate = Rate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rate.any_instance.stub(:save).and_return(false)
        put :update, :id => rate.id.to_s, :rate => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rate" do
      rate = Rate.create! valid_attributes
      expect {
        delete :destroy, :id => rate.id.to_s
      }.to change(Rate, :count).by(-1)
    end

    it "redirects to the rates list" do
      rate = Rate.create! valid_attributes
      delete :destroy, :id => rate.id.to_s
      response.should redirect_to(rates_url)
    end
  end

end
